# Generated by Django 4.2.7 on 2023-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.IntegerField()),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
