# Generated by Django 4.2.7 on 2023-11-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_faces_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='name',
        ),
        migrations.RemoveField(
            model_name='face',
            name='target',
        ),
    ]
