# Generated by Django 4.2.7 on 2023-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_face_name_remove_face_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='name',
            field=models.TextField(default='face'),
        ),
    ]
